version: '3.8'
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - USE_SSL=true
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
